---
- name: Transfer and execute a script.

  hosts: DHCL
  remote_user: test_user
  sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=foransible.sh dest=/home/dhcl mode=0777

     - name: Execute the script
       command: sh /home/test_user/foransible.sh
       register: result

     - name: Show result
       debug:
         msg: "{{ result.stdout }}"