---
- name: Transfer and execute a script.

  hosts: localhost
  #remote_user: test_user
  #sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=foransible.sh dest=/srv/ mode=0777

     - name: Execute the script
       shell: dcname | sh /srv/foransible.sh
       #register: "result"
       ignore_errors: true

     - name: Show result
       debug:
       ignore_errors: true
         #msg: "{{ result.stdout }}"

