---
- name: Transfer and execute a script.

  hosts: localhost
  #remote_user: test_user
  #sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=foransible.sh dest=/srv/ansible mode=0777

     - name: Execute the script
       command: yes | sh /srv/ansible/foransible.sh
       register: "result"
       ignore_errors: true

     - name: Show result
       debug:
       ignore_errors: true
         msg: "{{ result.stdout }}"

